name: Dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Native configure
        run: cmake -DCMAKE_BUILD_TYPE=RELEASE --target benchmark .

      - name: Native build
        run: make

      - name: Dependencies
        run: dart pub get

      - name: Compile
        run: dart compile exe bin/main.dart

      - name: Run
        run: bin/main.exe -c 1000000000
