name: Dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Dependencies
        run: dart pub get

      - name: Compile
        run: dart compile exe bin/main.dart

      - name: Run
        run: bin/main.exe -c 1000000000
